name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace this with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/setup-pages@v3

      - name: Build project
        run: echo "This is a static site deployment. No build step required."

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
